# Python wrapper code.
#
# Generated by SIP 3.10.2 (3.10.2-205) on Wed Mar 27 22:12:12 2019

import libsip
import libodsystemc

libodsystemc.sipInitModule(__name__)

class OdBody:
	def __init__(self,*args):
		libodsystemc.sipCallCtor(6,self,args)

class OdMarker:
	def __init__(self,*args):
		libodsystemc.sipCallCtor(5,self,args)

class OdJoint:
	def __init__(self,*args):
		libodsystemc.sipCallCtor(4,self,args)

class OdJointSPDP:
	def __init__(self,*args):
		libodsystemc.sipCallCtor(3,self,args)

class OdJointForce:
	def __init__(self,*args):
		libodsystemc.sipCallCtor(2,self,args)

class OdForce:
	def __init__(self,*args):
		libodsystemc.sipCallCtor(1,self,args)

class OdSystem:
	def __init__(self,*args):
		libodsystemc.sipCallCtor(0,self,args)

# Register the classes with the C++ module.

libodsystemc.sipRegisterClasses()
