// Module code.
//
// Generated by SIP 3.10.2 (3.10.2-205) on Wed Mar 27 22:12:12 2019

#include "sipodsystemDeclodsystem.h"

#include "sipodsystemOdBody.h"
#include "sipodsystemOdMarker.h"
#include "sipodsystemOdJoint.h"
#include "sipodsystemOdJointSPDP.h"
#include "sipodsystemOdJointForce.h"
#include "sipodsystemOdForce.h"
#include "sipodsystemOdSystem.h"

char sipName_numdif[] = "numdif";
char sipName_static_analysis[] = "static_analysis";
char sipName_kinematic_analysis[] = "kinematic_analysis";
char sipName_dynamic_analysis_bdf[] = "dynamic_analysis_bdf";
char sipName_dynamic_analysis_hht[] = "dynamic_analysis_hht";
char sipName_cpu_time[] = "cpu_time";
char sipName_acceleration_and_force_ic[] = "acceleration_and_force_ic";
char sipName_velocity_ic[] = "velocity_ic";
char sipName_displacement_ic[] = "displacement_ic";
char sipName_get_number_of_joints[] = "get_number_of_joints";
char sipName_get_number_of_bodies[] = "get_number_of_bodies";
char sipName_add_joint_spdp[] = "add_joint_spdp";
char sipName_add_joint_force[] = "add_joint_force";
char sipName_add_force[] = "add_force";
char sipName_add_constraint[] = "add_constraint";
char sipName_add_body[] = "add_body";
char sipName_setGravity[] = "setGravity";
char sipName_setName[] = "setName";
char sipName_OdSystem[] = "OdSystem";
char sipName_bushing[] = "bushing";
char sipName_beam[] = "beam";
char sipName_spdpt[] = "spdpt";
char sipName_storque[] = "storque";
char sipName_sforce[] = "sforce";
char sipName_set_gmodulus[] = "set_gmodulus";
char sipName_set_T[] = "set_T";
char sipName_set_F[] = "set_F";
char sipName_set_Cr[] = "set_Cr";
char sipName_set_Ct[] = "set_Ct";
char sipName_set_Kr[] = "set_Kr";
char sipName_set_Kt[] = "set_Kt";
char sipName_set_emodulus[] = "set_emodulus";
char sipName_set_ratio[] = "set_ratio";
char sipName_set_asz[] = "set_asz";
char sipName_set_asy[] = "set_asy";
char sipName_set_area[] = "set_area";
char sipName_set_izz[] = "set_izz";
char sipName_set_iyy[] = "set_iyy";
char sipName_set_ixx[] = "set_ixx";
char sipName_OdForce[] = "OdForce";
char sipName_OdJointForce[] = "OdJointForce";
char sipName_set_force[] = "set_force";
char sipName_set_distance[] = "set_distance";
char sipName_set_stiffness[] = "set_stiffness";
char sipName_set_damping[] = "set_damping";
char sipName_set_joint[] = "set_joint";
char sipName_OdJointSPDP[] = "OdJointSPDP";
char sipName_universal[] = "universal";
char sipName_spherical[] = "spherical";
char sipName_txyrz[] = "txyrz";
char sipName_translational[] = "translational";
char sipName_revolute[] = "revolute";
char sipName_free[] = "free";
char sipName_fixed[] = "fixed";
char sipName_set_expression[] = "set_expression";
char sipName_set_jmarker[] = "set_jmarker";
char sipName_set_imarker[] = "set_imarker";
char sipName_acc[] = "acc";
char sipName_vel[] = "vel";
char sipName_disp[] = "disp";
char sipName_OdJoint[] = "OdJoint";
char sipName_position_orientation[] = "position_orientation";
char sipName_orientation[] = "orientation";
char sipName_position[] = "position";
char sipName_set_angles[] = "set_angles";
char sipName_set_position[] = "set_position";
char sipName_set_omega[] = "set_omega";
char sipName_set_velocity[] = "set_velocity";
char sipName_OdMarker[] = "OdMarker";
char sipName_add_markerg[] = "add_markerg";
char sipName_add_marker[] = "add_marker";
char sipName_add_cm_marker[] = "add_cm_marker";
char sipName_info[] = "info";
char sipName_setI[] = "setI";
char sipName_setMass[] = "setMass";
char sipName_OdBody[] = "OdBody";

static sipClassDef classesTable[] = {
	{sipName_OdSystem, sipNew_OdSystem, &sipClass_OdSystem, &sipClassAttrTab_OdSystem, NULL, -1},
	{sipName_OdForce, sipNew_OdForce, &sipClass_OdForce, &sipClassAttrTab_OdForce, NULL, -1},
	{sipName_OdJointForce, sipNew_OdJointForce, &sipClass_OdJointForce, &sipClassAttrTab_OdJointForce, NULL, -1},
	{sipName_OdJointSPDP, sipNew_OdJointSPDP, &sipClass_OdJointSPDP, &sipClassAttrTab_OdJointSPDP, NULL, -1},
	{sipName_OdJoint, sipNew_OdJoint, &sipClass_OdJoint, &sipClassAttrTab_OdJoint, NULL, -1},
	{sipName_OdMarker, sipNew_OdMarker, &sipClass_OdMarker, &sipClassAttrTab_OdMarker, NULL, -1},
	{sipName_OdBody, sipNew_OdBody, &sipClass_OdBody, &sipClassAttrTab_OdBody, NULL, -1},
};

static sipModuleDef sipModule = {
	7,
	classesTable
};

// The entry point into the bindings for constructors.

static PyObject *callCtor(PyObject *,PyObject *args)
{
	return sipCallCtor(&sipModule,args);
}

// The entry point into the bindings for getting class variables.

static PyObject *callGetVar(PyObject *,PyObject *args)
{
	return sipGetVar(&sipModule,args);
}

// The entry point into the bindings for setting class variables.

static PyObject *callSetVar(PyObject *,PyObject *args)
{
	return sipSetVar(&sipModule,args);
}

// Initialise the module.

static PyObject *initModule(PyObject *,PyObject *args)
{
	if (sipRegisterModule(&sipModule,args) < 0)
		return NULL;

	Py_INCREF(Py_None);
	return Py_None;
}

// Final stage after the Python classes have been created.

static PyObject *registerClasses(PyObject *,PyObject *)
{
	if (sipRegisterClasses(&sipModule,-1) < 0)
		return NULL;

	Py_INCREF(Py_None);
	return Py_None;
}

// The Python module initialisation function.

extern "C" SIP_EXPORT void initlibodsystemc()
{
	static PyMethodDef methods[] = {
		{"sipCallCtor", callCtor, METH_VARARGS, NULL},
		{"sipCallGetVar", callGetVar, METH_VARARGS, NULL},
		{"sipCallSetVar", callSetVar, METH_VARARGS, NULL},
		{"sipInitModule", initModule, METH_VARARGS, NULL},
		{"sipRegisterClasses", registerClasses, METH_VARARGS, NULL},
		{NULL}
	};

	// Initialise the module.

	Py_InitModule("libodsystemc",methods);
}
