// C++ module API header file.
//
// Generated by SIP 3.10.2 (3.10.2-205) on Wed Mar 27 22:12:12 2019

#ifndef _odsystemEXPORTS_H
#define	_odsystemEXPORTS_H

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <sip.h>

#line 4 "python\od_system.sip"
#include <string>
#include <iostream>
#include "od_marker_api.h"
#include "od_constraint_api.h"
#include "od_body_api.h"
#include "od_force_api.h"
#include "od_system_api.h"
#include "od_subsystem_api.h"
#include "expr.h"
#line 25 "sipodsystemDeclodsystem.h"
extern SIP_MODULE_EXTERN PyObject *sipClass_OdSystem;
extern SIP_MODULE_EXTERN PyObject *sipClass_OdForce;
extern SIP_MODULE_EXTERN PyObject *sipClass_OdJointForce;
extern SIP_MODULE_EXTERN PyObject *sipClass_OdJointSPDP;
extern SIP_MODULE_EXTERN PyObject *sipClass_OdJoint;
extern SIP_MODULE_EXTERN PyObject *sipClass_OdMarker;
extern SIP_MODULE_EXTERN PyObject *sipClass_OdBody;

extern SIP_MODULE_EXTERN char sipName_numdif[];
extern SIP_MODULE_EXTERN char sipName_static_analysis[];
extern SIP_MODULE_EXTERN char sipName_kinematic_analysis[];
extern SIP_MODULE_EXTERN char sipName_dynamic_analysis_bdf[];
extern SIP_MODULE_EXTERN char sipName_dynamic_analysis_hht[];
extern SIP_MODULE_EXTERN char sipName_cpu_time[];
extern SIP_MODULE_EXTERN char sipName_acceleration_and_force_ic[];
extern SIP_MODULE_EXTERN char sipName_velocity_ic[];
extern SIP_MODULE_EXTERN char sipName_displacement_ic[];
extern SIP_MODULE_EXTERN char sipName_get_number_of_joints[];
extern SIP_MODULE_EXTERN char sipName_get_number_of_bodies[];
extern SIP_MODULE_EXTERN char sipName_add_joint_spdp[];
extern SIP_MODULE_EXTERN char sipName_add_joint_force[];
extern SIP_MODULE_EXTERN char sipName_add_force[];
extern SIP_MODULE_EXTERN char sipName_add_constraint[];
extern SIP_MODULE_EXTERN char sipName_add_body[];
extern SIP_MODULE_EXTERN char sipName_setGravity[];
extern SIP_MODULE_EXTERN char sipName_setName[];
extern SIP_MODULE_EXTERN char sipName_OdSystem[];
extern SIP_MODULE_EXTERN char sipName_bushing[];
extern SIP_MODULE_EXTERN char sipName_beam[];
extern SIP_MODULE_EXTERN char sipName_spdpt[];
extern SIP_MODULE_EXTERN char sipName_storque[];
extern SIP_MODULE_EXTERN char sipName_sforce[];
extern SIP_MODULE_EXTERN char sipName_set_gmodulus[];
extern SIP_MODULE_EXTERN char sipName_set_T[];
extern SIP_MODULE_EXTERN char sipName_set_F[];
extern SIP_MODULE_EXTERN char sipName_set_Cr[];
extern SIP_MODULE_EXTERN char sipName_set_Ct[];
extern SIP_MODULE_EXTERN char sipName_set_Kr[];
extern SIP_MODULE_EXTERN char sipName_set_Kt[];
extern SIP_MODULE_EXTERN char sipName_set_emodulus[];
extern SIP_MODULE_EXTERN char sipName_set_ratio[];
extern SIP_MODULE_EXTERN char sipName_set_asz[];
extern SIP_MODULE_EXTERN char sipName_set_asy[];
extern SIP_MODULE_EXTERN char sipName_set_area[];
extern SIP_MODULE_EXTERN char sipName_set_izz[];
extern SIP_MODULE_EXTERN char sipName_set_iyy[];
extern SIP_MODULE_EXTERN char sipName_set_ixx[];
extern SIP_MODULE_EXTERN char sipName_OdForce[];
extern SIP_MODULE_EXTERN char sipName_OdJointForce[];
extern SIP_MODULE_EXTERN char sipName_set_force[];
extern SIP_MODULE_EXTERN char sipName_set_distance[];
extern SIP_MODULE_EXTERN char sipName_set_stiffness[];
extern SIP_MODULE_EXTERN char sipName_set_damping[];
extern SIP_MODULE_EXTERN char sipName_set_joint[];
extern SIP_MODULE_EXTERN char sipName_OdJointSPDP[];
extern SIP_MODULE_EXTERN char sipName_universal[];
extern SIP_MODULE_EXTERN char sipName_spherical[];
extern SIP_MODULE_EXTERN char sipName_txyrz[];
extern SIP_MODULE_EXTERN char sipName_translational[];
extern SIP_MODULE_EXTERN char sipName_revolute[];
extern SIP_MODULE_EXTERN char sipName_free[];
extern SIP_MODULE_EXTERN char sipName_fixed[];
extern SIP_MODULE_EXTERN char sipName_set_expression[];
extern SIP_MODULE_EXTERN char sipName_set_jmarker[];
extern SIP_MODULE_EXTERN char sipName_set_imarker[];
extern SIP_MODULE_EXTERN char sipName_acc[];
extern SIP_MODULE_EXTERN char sipName_vel[];
extern SIP_MODULE_EXTERN char sipName_disp[];
extern SIP_MODULE_EXTERN char sipName_OdJoint[];
extern SIP_MODULE_EXTERN char sipName_position_orientation[];
extern SIP_MODULE_EXTERN char sipName_orientation[];
extern SIP_MODULE_EXTERN char sipName_position[];
extern SIP_MODULE_EXTERN char sipName_set_angles[];
extern SIP_MODULE_EXTERN char sipName_set_position[];
extern SIP_MODULE_EXTERN char sipName_set_omega[];
extern SIP_MODULE_EXTERN char sipName_set_velocity[];
extern SIP_MODULE_EXTERN char sipName_OdMarker[];
extern SIP_MODULE_EXTERN char sipName_add_markerg[];
extern SIP_MODULE_EXTERN char sipName_add_marker[];
extern SIP_MODULE_EXTERN char sipName_add_cm_marker[];
extern SIP_MODULE_EXTERN char sipName_info[];
extern SIP_MODULE_EXTERN char sipName_setI[];
extern SIP_MODULE_EXTERN char sipName_setMass[];
extern SIP_MODULE_EXTERN char sipName_OdBody[];

#endif
