// C++ interface header file.
//
// Generated by SIP 3.10.2 (3.10.2-205) on Wed Mar 27 22:12:12 2019

#ifndef _odsystemOdSystem_h
#define	_odsystemOdSystem_h


#include "sipodsystemOdJointSPDP.h"
#include "sipodsystemOdJointForce.h"
#include "sipodsystemOdForce.h"
#include "sipodsystemOdJoint.h"
#include "sipodsystemOdBody.h"


extern SIP_MODULE_EXTERN sipLazyAttrDef sipClassAttrTab_OdSystem;

extern SIP_MODULE_EXTERN const void *sipCast_OdSystem Py_PROTO((const void *,PyObject *));
extern SIP_MODULE_EXTERN PyObject *sipNew_OdSystem Py_PROTO((PyObject *,PyObject *));

extern SIP_MODULE_EXTERN OdSystem *sipForceConvertTo_OdSystem Py_PROTO((PyObject *,int *));

#endif
