// C++ interface header file.
//
// Generated by SIP 3.10.2 (3.10.2-205) on Wed Mar 27 22:12:12 2019

#ifndef _odsystemOdMarker_h
#define	_odsystemOdMarker_h


#include "sipodsystemOdBody.h"


extern SIP_MODULE_EXTERN sipLazyAttrDef sipClassAttrTab_OdMarker;

extern SIP_MODULE_EXTERN const void *sipCast_OdMarker Py_PROTO((const void *,PyObject *));
extern SIP_MODULE_EXTERN PyObject *sipNew_OdMarker Py_PROTO((PyObject *,PyObject *));

extern SIP_MODULE_EXTERN OdMarker *sipForceConvertTo_OdMarker Py_PROTO((PyObject *,int *));

#endif
