// C++ interface header file.
//
// Generated by SIP 3.10.2 (3.10.2-205) on Wed Mar 27 22:12:12 2019

#ifndef _odsystemOdJointForce_h
#define	_odsystemOdJointForce_h


#include "sipodsystemOdJoint.h"


extern SIP_MODULE_EXTERN sipLazyAttrDef sipClassAttrTab_OdJointForce;

extern SIP_MODULE_EXTERN const void *sipCast_OdJointForce Py_PROTO((const void *,PyObject *));
extern SIP_MODULE_EXTERN PyObject *sipNew_OdJointForce Py_PROTO((PyObject *,PyObject *));

extern SIP_MODULE_EXTERN OdJointForce *sipForceConvertTo_OdJointForce Py_PROTO((PyObject *,int *));

#endif
