// C++ interface header file.
//
// Generated by SIP 3.10.2 (3.10.2-205) on Wed Mar 27 22:12:12 2019

#ifndef _odsystemOdForce_h
#define	_odsystemOdForce_h


#include "sipodsystemOdMarker.h"


extern SIP_MODULE_EXTERN sipLazyAttrDef sipClassAttrTab_OdForce;

extern SIP_MODULE_EXTERN const void *sipCast_OdForce Py_PROTO((const void *,PyObject *));
extern SIP_MODULE_EXTERN PyObject *sipNew_OdForce Py_PROTO((PyObject *,PyObject *));

extern SIP_MODULE_EXTERN OdForce *sipForceConvertTo_OdForce Py_PROTO((PyObject *,int *));

#endif
