%Steps taken 20
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  1.0090e-02  1.1000e-03     2        40         3 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 29
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  2.0870e-02  1.2100e-03     3        58         5 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 31
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  3.4180e-02  1.2100e-02     3        62         7 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 32
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  4.6280e-02  1.2100e-02     3        64         8 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 33
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  5.8380e-02  1.2100e-02     3        66         9 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 34
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  7.0480e-02  1.2100e-02     3        68        10 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 35
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  8.2580e-02  1.2100e-02     3        70        11 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 36
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  9.4680e-02  1.2100e-02     3        72        12 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 37
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  1.0678e-01  1.2100e-02     3        74        13 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 38
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  1.1888e-01  1.2100e-02     3        76        14 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 39
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  1.3098e-01  5.8507e-02     3        78        15 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 40
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  1.8949e-01  5.8507e-02     3        80        16 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 41
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  2.4799e-01  5.8507e-02     3        82        17 -3.9194e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 42
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  3.0650e-01  5.8507e-02     3        84        18 -3.9192e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 43
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  3.6501e-01  5.8507e-02     3        86        19 -3.9188e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 44
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  4.1248e-01  4.7476e-02     3        90        21 -3.9185e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 45
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  4.5996e-01  4.7476e-02     3        92        22 -3.9187e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 46
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  5.0743e-01  4.7476e-02     3        94        23 -3.9210e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 47
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  5.3613e-01  2.8691e-02     3        98        25 -3.9228e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 48
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  5.5332e-01  1.7197e-02     2       104        28 -3.9242e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 49
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  5.6756e-01  1.4235e-02     2       108        30 -3.9255e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 50
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  5.8179e-01  1.4235e-02     2       110        31 -3.9271e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 51
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  5.9603e-01  1.4235e-02     2       112        32 -3.9290e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 52
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  6.1026e-01  1.4235e-02     2       114        33 -3.9308e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 53
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  6.2450e-01  1.4235e-02     2       116        34 -3.9323e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 54
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  6.3873e-01  1.4235e-02     2       118        35 -3.9332e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 55
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  6.5297e-01  1.4235e-02     2       120        36 -3.9332e+01  0.0000e+00  0.0000e+00  0.0000e+00;
%Steps taken 56
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  6.6720e-01  1.4235e-02     2       122        37 -3.9324e+01  0.0000e+00  1.5625e-02  0.0000e+00;
%Steps taken 57
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  6.8144e-01  1.4235e-02     2       124        38 -3.9309e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 58
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  6.9567e-01  1.4235e-02     2       126        39 -3.9292e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 59
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  7.0991e-01  1.4235e-02     2       128        40 -3.9274e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 60
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  7.2414e-01  1.4235e-02     2       130        41 -3.9258e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 61
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  7.3838e-01  1.4235e-02     2       132        42 -3.9245e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 62
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  7.5261e-01  1.4235e-02     2       134        43 -3.9235e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 63
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  7.6685e-01  1.4235e-02     2       136        44 -3.9228e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 64
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  7.8108e-01  1.4235e-02     2       138        45 -3.9224e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 65
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  7.9532e-01  1.4235e-02     2       140        46 -3.9221e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 66
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  8.0955e-01  2.9810e-02     2       142        47 -3.9220e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 67
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  8.3936e-01  2.9810e-02     2       144        48 -3.9218e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 68
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  8.6917e-01  2.9810e-02     2       146        49 -3.9220e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 69
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  8.9898e-01  2.9810e-02     2       148        50 -3.9225e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 70
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  9.2879e-01  2.9810e-02     2       150        51 -3.9230e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 71
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  9.5860e-01  2.9810e-02     2       152        52 -3.9235e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 72
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  9.8841e-01  2.9810e-02     2       154        53 -3.9239e+01  1.5625e-02  1.5625e-02  0.0000e+00;
%Steps taken 73
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  1.0182e+00  2.9810e-02     2       156        54 -3.9243e+01  1.5625e-02  1.5625e-02  0.0000e+00;
