%Steps taken 151
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  1.0057e-02  1.1331e-04     5       416        29 -9.5964e+05  0.0000e+00  1.5625e-02  1.5625e-02;
%Steps taken 253
       %Time    StepSize Order       rhs       jac         KPE         Cpu      JacCpu      RhsCPU
  2.0016e-02  8.9941e-05     4       659        46 -1.4601e+06  3.1250e-02  1.5625e-02  1.5625e-02;
